// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL94qeLveCTgDRNvaU3AOM-LMygX9qVws',
    appId: '1:506651509967:web:720bd624c95b7f315063ba',
    messagingSenderId: '506651509967',
    projectId: 'rxpro-mobile-202605172210',
    authDomain: 'rxpro-mobile-202605172210.firebaseapp.com',
    storageBucket: 'rxpro-mobile-202605172210.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtB_kRmAyeaUVIdDYKdDTg-6pSm6NIm7Y',
    appId: '1:506651509967:android:f5b6a2743a57402a5063ba',
    messagingSenderId: '506651509967',
    projectId: 'rxpro-mobile-202605172210',
    storageBucket: 'rxpro-mobile-202605172210.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDykA_fDTjAhMyPbSzzV12l1n_HnTRr8CE',
    appId: '1:506651509967:ios:7fc11d03ddcb9d2b5063ba',
    messagingSenderId: '506651509967',
    projectId: 'rxpro-mobile-202605172210',
    storageBucket: 'rxpro-mobile-202605172210.firebasestorage.app',
    iosBundleId: 'com.fix.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDykA_fDTjAhMyPbSzzV12l1n_HnTRr8CE',
    appId: '1:506651509967:ios:7fc11d03ddcb9d2b5063ba',
    messagingSenderId: '506651509967',
    projectId: 'rxpro-mobile-202605172210',
    storageBucket: 'rxpro-mobile-202605172210.firebasestorage.app',
    iosBundleId: 'com.fix.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL94qeLveCTgDRNvaU3AOM-LMygX9qVws',
    appId: '1:506651509967:web:8e0a05b9a034e0125063ba',
    messagingSenderId: '506651509967',
    projectId: 'rxpro-mobile-202605172210',
    authDomain: 'rxpro-mobile-202605172210.firebaseapp.com',
    storageBucket: 'rxpro-mobile-202605172210.firebasestorage.app',
  );
}
