import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:rxpro_mobile/core/firestore/firestore_collections.dart';
import 'package:rxpro_mobile/core/firestore/firestore_fields.dart';

/// 51B-K: Foundation repository for business finance reads/writes.
///
/// This class is intentionally not wired into BusinessFinancePage yet.
/// Current UI behavior stays unchanged. Next phases can migrate reads first,
/// then writes, while preserving legacy financeRecords/businessExpenses data.
class BusinessFinanceRepository {
  BusinessFinanceRepository({FirebaseFirestore? firestore})
    : _db = firestore ?? FirebaseFirestore.instance;

  static const int _financeSnapshotWindow = 180;

  final FirebaseFirestore _db;

  CollectionReference<Map<String, dynamic>> get _financeRecords =>
      _db.collection(FirestoreCollections.financeRecords);

  CollectionReference<Map<String, dynamic>> get _businessExpenses =>
      _db.collection(FirestoreCollections.businessExpenses);

  CollectionReference<Map<String, dynamic>> get _appointments =>
      _db.collection(FirestoreCollections.appointments);

  /// 51B-M: Read-only helper for the active BusinessFinancePage.
  ///
  /// This intentionally preserves the old page behavior:
  /// - businessId filter is applied when available.
  /// - month filtering stays in BusinessFinancePage because legacy rows may not
  ///   always contain monthKey and the page has fallback date parsing.
  /// - write behavior is unchanged.
  Future<QuerySnapshot<Map<String, dynamic>>> fetchBusinessExpensesSnapshot({
    required String businessId,
    int limit = _financeSnapshotWindow,
  }) {
    Query<Map<String, dynamic>> query = _businessExpenses;

    final cleanBusinessId = businessId.trim();
    if (cleanBusinessId.isNotEmpty) {
      query = query.where(
        FirestoreFields.businessId,
        isEqualTo: cleanBusinessId,
      );
    }

    return query.limit(limit).get();
  }

  /// 51B-M: Read-only helper for income records generated by FinanceRecordService.
  ///
  /// Keeps the existing BusinessFinancePage query semantics:
  /// - recordType == income
  /// - optional businessId filter
  /// - no orderBy/index-changing behavior
  /// - no writes
  Future<QuerySnapshot<Map<String, dynamic>>>
  fetchIncomeFinanceRecordsSnapshot({
    required String businessId,
    int limit = _financeSnapshotWindow,
  }) {
    Query<Map<String, dynamic>> query = _financeRecords.where(
      FirestoreFields.recordType,
      isEqualTo: 'income',
    );

    final cleanBusinessId = businessId.trim();
    if (cleanBusinessId.isNotEmpty) {
      query = query.where(
        FirestoreFields.businessId,
        isEqualTo: cleanBusinessId,
      );
    }

    return query.limit(limit).get();
  }

  /// 51B-M: Read-only fallback helper for legacy appointment-derived income.
  ///
  /// BusinessFinancePage still uses this only when financeRecords income rows
  /// are empty, matching the pre-migration fallback behavior.
  Future<QuerySnapshot<Map<String, dynamic>>>
  fetchBusinessAppointmentsSnapshot({
    required String businessId,
    int limit = _financeSnapshotWindow,
  }) {
    Query<Map<String, dynamic>> query = _appointments;

    final cleanBusinessId = businessId.trim();
    if (cleanBusinessId.isNotEmpty) {
      query = query.where(
        FirestoreFields.businessId,
        isEqualTo: cleanBusinessId,
      );
    }

    return query.limit(limit).get();
  }

  Query<Map<String, dynamic>> businessFinanceRecordsQuery({
    required String businessId,
    String? monthKey,
  }) {
    Query<Map<String, dynamic>> query = _financeRecords.where(
      FirestoreFields.businessId,
      isEqualTo: businessId,
    );

    if (monthKey != null && monthKey.trim().isNotEmpty) {
      query = query.where(FirestoreFields.monthKey, isEqualTo: monthKey.trim());
    }

    return query;
  }

  Query<Map<String, dynamic>> businessExpensesQuery({
    required String businessId,
    String? monthKey,
  }) {
    Query<Map<String, dynamic>> query = _businessExpenses.where(
      FirestoreFields.businessId,
      isEqualTo: businessId,
    );

    if (monthKey != null && monthKey.trim().isNotEmpty) {
      query = query.where(FirestoreFields.monthKey, isEqualTo: monthKey.trim());
    }

    return query;
  }

  Stream<List<BusinessFinanceRecord>> watchIncomeRecords({
    required String businessId,
    String? monthKey,
  }) {
    return businessFinanceRecordsQuery(
      businessId: businessId,
      monthKey: monthKey,
    ).snapshots().map(
      (snapshot) => snapshot.docs
          .map((doc) => BusinessFinanceRecord.fromDoc(doc))
          .toList(growable: false),
    );
  }

  Stream<List<BusinessExpenseRecord>> watchExpenseRecords({
    required String businessId,
    String? monthKey,
  }) {
    return businessExpensesQuery(
      businessId: businessId,
      monthKey: monthKey,
    ).snapshots().map(
      (snapshot) => snapshot.docs
          .map((doc) => BusinessExpenseRecord.fromDoc(doc))
          .toList(growable: false),
    );
  }

  Stream<BusinessFinanceSummary> watchSummary({
    required String businessId,
    String? monthKey,
  }) {
    return watchIncomeRecords(
      businessId: businessId,
      monthKey: monthKey,
    ).asyncMap((incomeRecords) async {
      final expensesSnapshot = await businessExpensesQuery(
        businessId: businessId,
        monthKey: monthKey,
      ).get();

      final expenses = expensesSnapshot.docs
          .map((doc) => BusinessExpenseRecord.fromDoc(doc))
          .toList(growable: false);

      return BusinessFinanceSummary.fromRecords(
        incomeRecords: incomeRecords,
        expenseRecords: expenses,
      );
    });
  }

  Future<DocumentReference<Map<String, dynamic>>> addBusinessExpense({
    required String businessId,
    required String businessName,
    required String title,
    required double amount,
    required String category,
    String note = '',
    bool isRecurring = false,
    String recurringPeriod = '',
    DateTime? now,
    String source = 'business_finance_repository_51B_K',
  }) {
    final createdAt = now ?? DateTime.now();
    final monthKey = _monthKey(createdAt);

    return _businessExpenses.add({
      FirestoreFields.businessId: businessId,
      FirestoreFields.businessName: businessName,
      FirestoreFields.title: title,
      FirestoreFields.expenseName: title,
      FirestoreFields.amount: amount,
      FirestoreFields.category: category,
      FirestoreFields.note: note,
      FirestoreFields.isRecurring: isRecurring,
      FirestoreFields.recurringPeriod: isRecurring ? recurringPeriod : '',
      FirestoreFields.periodResetDay: createdAt.day,
      FirestoreFields.expenseDate: _dateText(createdAt),
      FirestoreFields.expenseDateIso: createdAt.toIso8601String(),
      FirestoreFields.createdAtLocalIso: createdAt.toIso8601String(),
      FirestoreFields.monthKey: monthKey,
      FirestoreFields.createdAt: FieldValue.serverTimestamp(),
      FirestoreFields.updatedAt: FieldValue.serverTimestamp(),
      FirestoreFields.source: source,
    });
  }

  static String _monthKey(DateTime value) {
    final month = value.month.toString().padLeft(2, '0');
    return '${value.year}-$month';
  }

  static String _dateText(DateTime value) {
    final day = value.day.toString().padLeft(2, '0');
    final month = value.month.toString().padLeft(2, '0');
    return '$day.$month.${value.year}';
  }
}

class BusinessFinanceRecord {
  const BusinessFinanceRecord({
    required this.id,
    required this.businessId,
    required this.amount,
    required this.paymentStatus,
    required this.recordType,
    this.appointmentId,
    this.serviceId,
    this.serviceName,
    this.staffUid,
    this.staffName,
    this.customerName,
    this.monthKey,
  });

  final String id;
  final String businessId;
  final double amount;
  final String paymentStatus;
  final String recordType;
  final String? appointmentId;
  final String? serviceId;
  final String? serviceName;
  final String? staffUid;
  final String? staffName;
  final String? customerName;
  final String? monthKey;

  factory BusinessFinanceRecord.fromDoc(
    QueryDocumentSnapshot<Map<String, dynamic>> doc,
  ) {
    final data = doc.data();
    return BusinessFinanceRecord(
      id: _stringValue(data[FirestoreFields.id], fallback: doc.id),
      businessId: _stringValue(data[FirestoreFields.businessId]),
      amount: _doubleValue(data[FirestoreFields.amount]),
      paymentStatus: _stringValue(data[FirestoreFields.paymentStatus]),
      recordType: _stringValue(data[FirestoreFields.recordType]),
      appointmentId: _nullableString(data[FirestoreFields.appointmentId]),
      serviceId: _nullableString(data[FirestoreFields.serviceId]),
      serviceName: _nullableString(data[FirestoreFields.serviceName]),
      staffUid: _nullableString(data[FirestoreFields.staffUid]),
      staffName: _nullableString(data[FirestoreFields.staffName]),
      customerName: _nullableString(data[FirestoreFields.customerName]),
      monthKey: _nullableString(data[FirestoreFields.monthKey]),
    );
  }
}

class BusinessExpenseRecord {
  const BusinessExpenseRecord({
    required this.id,
    required this.businessId,
    required this.title,
    required this.amount,
    required this.category,
    this.note,
    this.monthKey,
    this.isRecurring = false,
  });

  final String id;
  final String businessId;
  final String title;
  final double amount;
  final String category;
  final String? note;
  final String? monthKey;
  final bool isRecurring;

  factory BusinessExpenseRecord.fromDoc(
    QueryDocumentSnapshot<Map<String, dynamic>> doc,
  ) {
    final data = doc.data();
    return BusinessExpenseRecord(
      id: doc.id,
      businessId: _stringValue(data[FirestoreFields.businessId]),
      title: _stringValue(
        data[FirestoreFields.title] ?? data[FirestoreFields.expenseName],
      ),
      amount: _doubleValue(data[FirestoreFields.amount]),
      category: _stringValue(data[FirestoreFields.category]),
      note: _nullableString(data[FirestoreFields.note]),
      monthKey: _nullableString(data[FirestoreFields.monthKey]),
      isRecurring: data[FirestoreFields.isRecurring] == true,
    );
  }
}

class BusinessFinanceSummary {
  const BusinessFinanceSummary({
    required this.totalIncome,
    required this.totalExpense,
  });

  final double totalIncome;
  final double totalExpense;

  double get netProfit => totalIncome - totalExpense;

  factory BusinessFinanceSummary.fromRecords({
    required List<BusinessFinanceRecord> incomeRecords,
    required List<BusinessExpenseRecord> expenseRecords,
  }) {
    final totalIncome = incomeRecords.fold<double>(
      0,
      (total, item) => total + item.amount,
    );
    final totalExpense = expenseRecords.fold<double>(
      0,
      (total, item) => total + item.amount,
    );

    return BusinessFinanceSummary(
      totalIncome: totalIncome,
      totalExpense: totalExpense,
    );
  }
}

String _stringValue(Object? value, {String fallback = ''}) {
  if (value == null) return fallback;
  final text = value.toString().trim();
  return text.isEmpty ? fallback : text;
}

String? _nullableString(Object? value) {
  if (value == null) return null;
  final text = value.toString().trim();
  return text.isEmpty ? null : text;
}

double _doubleValue(Object? value) {
  if (value is num) return value.toDouble();
  return double.tryParse(value?.toString() ?? '') ?? 0;
}
